import tkinter as tk
from tkinter import W, E, N, S, messagebox
from PIL import Image, ImageTk
from dbquery import *
def show_frame(frame):
    frame.tkraise()
def WindowsTK():
    window = tk.Tk()
    window.geometry('800x600')
    window.resizable(False, False)
    window.title('PassSaver')
    original_image = Image.open(r"C:\Users\zange\source\repos\Zhan-Gabriel-Gerke\project-test\FinalWork\background.jpg")
    resized_image = original_image.resize((800, 600))
    bgimage = ImageTk.PhotoImage(resized_image)
    container = tk.Frame(window)
    container.pack(fill="both", expand=True)
    frame_create = tk.Frame(container, bg="lightblue")
    frame_log_in = tk.Frame(container, bg="lightgreen")
    frame_start = tk.Frame(container)
    for frame in (frame_create, frame_log_in, frame_start):
        frame.place(relwidth=1, relheight=1)
    labelBG= tk.Label(frame_start,image=bgimage)
    labelBG.place(x=0,y=0)
    labelBG= tk.Label(frame_log_in,image=bgimage)
    labelBG.place(x=0,y=0)
    labelBG= tk.Label(frame_create,image=bgimage)
    labelBG.place(x=0,y=0)
    welcome_lable = tk.Label(frame_start, bg='gray', text='PassKeeper', font=('Arial', 30, 'bold'))
    welcome_lable.place(x=300, y=80)
    Button_create = tk.Button(frame_start, text='Create new account', font=('Arial', 15, 'bold'), bg='gray', command=lambda: show_frame(frame_create))
    Button_create.place(x=320, y=200)
    Button_log_in = tk.Button(frame_start, text='Log In', font=('Arial', 15, 'bold'), bg='gray', command=lambda: show_frame(frame_log_in))
    Button_log_in.place(x=380, y=250)
    log_in_lable = tk.Label(frame_log_in, bg='gray', text='Log In', font=('Arial', 30, 'bold'))
    log_in_lable.place(x=350, y=50)
    create_new_accoun_lable = tk.Label(frame_create, bg='gray', text='Create new account', font=('Arial', 30, 'bold'))
    create_new_accoun_lable.place(x=250, y=50)
    Button_back_login = tk.Button(frame_log_in, text='Back', font=('Arial', 15, 'bold'), bg='gray', command=lambda: show_frame(frame_start))
    Button_back_login.place(x=700, y=550)
    Button_back_login = tk.Button(frame_create, text='Back', font=('Arial', 15, 'bold'), bg='gray', command=lambda: show_frame(frame_start))
    Button_back_login.place(x=700, y=550)
    show_frame(frame_start)
    window.mainloop()